import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import CartProvider from "./providers";
import ShoppingCartModal from "@/app/ShoppingCartModal";
import { WishlistProvider } from "./wishlistcomponent/wishlistcontext";
import {
  ClerkProvider,
  } from '@clerk/nextjs'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WishlistProvider>
        <CartProvider>
          <Navbar />
          <ShoppingCartModal/>
          {children}
          <Footer />
        </CartProvider>
        </WishlistProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
